# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TicTacToe' do
  # Comment the next line if you don't want to use dynamic frameworks
  # use_frameworks!
  use_modular_headers!
  
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'ObjectMapper', '~> 3.1'
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SwiftIcons', '~> 3.0'
  pod 'Socket.IO-Client-Swift', '~> 15.2.0'
  pod 'ChameleonFramework'
  pod 'IQKeyboardManagerSwift', '6.3.0'
  pod 'SwiftyJSON', '~> 4.0'
#  pod 'RHSideButtons'
  pod 'NewPopMenu', '~> 2.0'
  pod 'PopupDialog', '~> 1.1'
  pod 'JJFloatingActionButton'
  pod 'SwiftMessages'
  pod 'NVActivityIndicatorView'
#  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
  
  # Pods for TicTacToe

  target 'TicTacToeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TicTacToeUITests' do
    # Pods for testing
  end

end
